# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# hook_add = 'let g:deoplete#enable_at_startup = 1'

# neosnippet は snippet 本体
[[plugins]]
repo = 'Shougo/neosnippet.vim'

# 以下はスニペットを集めたファイル群
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# ウィンドウサイズの変更、 `<C-w>>` を簡単にしたい為
# https://qiita.com/tekkoc/items/98adcadfa4bdc8b5a6ca
[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'scrooloose/nerdtree'

#[[plugins]]
# メンテされてない!?
#repo = 'jistr/vim-nerdtree-tabs'

# [[plugins]]
# repo = 'mortonfox/nerdtree-iterm'

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# hook_add = 'let g:indent_guides_enable_on_vim_startup = 1'

# 複数行のコメントON/OFF : ctlf + --
[[plugins]]
repo = 'tomtom/tcomment_vim'

# '%' による括弧の対応付け
[[plugins]]
repo = 'vim-scripts/ruby-matchit'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
