# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# hook_add = 'let g:deoplete#enable_at_startup = 1'

# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
#
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'scrooloose/nerdtree'

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# hook_add = 'let g:indent_guides_enable_on_vim_startup = 1'
